
/**************
* This source file was generated by JUndo compiler version 070812A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Mon Jan 28 09:41:20 MST 2008
* From Input File : VibratoViewPaneModel.JUndo
**************/

package labdaw.undo;

public class pdx_VibratoViewPaneModel_pdx_PairRef extends jundo.runtime.ExtPair
	{
public pdx_VibratoViewPaneModel_pdx_PairRef( pdx_VibratoViewPaneModel_pdx_ObjectRef obj , jundo.runtime.ExtMilieuRef mil )
{
super( obj , mil );
}
	}

