
/**************
* This source file was generated by JUndo compiler version 070812A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Wed Mar 23 12:40:13 MDT 2011
* From Input File : /Users/thorngreen/svngogl/ddt/trunk/osgi.SndHnd/src/labdaw/undo/PiecewiseCubicMonotoneUnitPeriodicBezierViewPaneModel.JUndo
**************/

package labdaw.undo;

public class pdx_PiecewiseCubicMonotoneUnitPeriodicBezierViewPaneModel_pdx_PairRef extends jundo.runtime.ExtPair
	{
public pdx_PiecewiseCubicMonotoneUnitPeriodicBezierViewPaneModel_pdx_PairRef( pdx_PiecewiseCubicMonotoneUnitPeriodicBezierViewPaneModel_pdx_ObjectRef obj , jundo.runtime.ExtMilieuRef mil )
{
super( obj , mil );
}
	}

