
/**************
* This source file was generated by JUndo compiler version 070812A.
* JUndo is a declarative object-oriented programming language with 
* functional, and intensional programming characteristics.
* See http://sourceforge.net/projects/jundo
* Do not modify this file directly.  Instead, modify the .JUndo file
* and recompile.  See the associated .JUndo file for license and
* copyright information.
* This File Generated : Mon Jan 28 10:17:42 MST 2008
* From Input File : TempoViewPaneModel.JUndo
**************/

package labdaw.undo;

public class pdx_TempoViewPaneModel_pdx_ObjectRef extends jundo.runtime.ExtObjectRef
	{
protected pdx_TempoViewPaneModel_pdx_ObjectRef( jundo.runtime.KeyRef Key )
{
super( Key );
}

public static labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef createOID_TempoViewPaneModel( jundo.runtime.ExtMilieuRef InMil )
{
jundo.runtime.ExtMilieuRef NewMil = jundo.runtime.Runtime.createOIDmilieu( InMil );
int NewID = NewMil.getMaxID();
jundo.runtime.KeyRef MyKey = jundo.runtime.Runtime.getKeyRef( NewID );
pdx_TempoViewPaneModel_pdx_ObjectRef NewObj = 
	new pdx_TempoViewPaneModel_pdx_ObjectRef( MyKey );
labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef ret = new labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef( NewObj , NewMil );
return( ret );
}
	public static labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef pdxm_new_TempoViewPaneModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final double  startSeconds , final double  endSeconds , final double  startTempo , final double  endTempo )
{
final labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef pdx_tmp_3162 = labdaw.undo.pdx_TempoViewPaneModel_pdx_ObjectRef.pdxm_allocate_TempoViewPaneModel( ( pdx_thismilieu ) );
final labdaw.undo.pdx_TempoViewPaneModel_pdx_ObjectRef pdx_tmp_3160 = (labdaw.undo.pdx_TempoViewPaneModel_pdx_ObjectRef)( pdx_tmp_3162.getObject() );
final jundo.runtime.ExtMilieuRef pdx_tmp_3161 = pdx_tmp_3162.getMilieu();
final jundo.runtime.ExtMilieuRef pdx_tmp_3480 = pdx_tmp_3160.pdxm_setStartSecondsNumber( pdx_tmp_3161 , ( startSeconds ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_3640 = pdx_tmp_3160.pdxm_setEndSecondsNumber( pdx_tmp_3480 , ( endSeconds ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_3800 = pdx_tmp_3160.pdxm_setStartTempo( pdx_tmp_3640 , ( startTempo ) );
final jundo.runtime.ExtMilieuRef pdx_tmp_3960 = pdx_tmp_3160.pdxm_setEndTempo( pdx_tmp_3800 , ( endTempo ) );
return( new labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef( pdx_tmp_3160 , ( pdx_tmp_3960 ) ) );
}
	public static labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef pdxm_allocate_TempoViewPaneModel( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef t1 = pdx_TempoViewPaneModel_pdx_ObjectRef.createOID_TempoViewPaneModel( pdx_thismilieu );
final labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef t2 = pdx_zero( t1.getMilieu() , (labdaw.undo.pdx_TempoViewPaneModel_pdx_ObjectRef)( t1.getObject() ) );

return( t2 );
}
	public static labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef pdx_zero( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final labdaw.undo.pdx_TempoViewPaneModel_pdx_ObjectRef in )
{
final labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef tx = new labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef( in , pdx_thismilieu );
final jundo.runtime.ExtMilieuRef t0 = tx.getMilieu();
final jundo.runtime.ExtMilieuRef t1 = jundo.runtime.Runtime.asgDoubleObjectMember( tx.getObject() , "endSecondsNumber" , t0 , 0 );
final jundo.runtime.ExtMilieuRef t2 = jundo.runtime.Runtime.asgDoubleObjectMember( tx.getObject() , "startSecondsNumber" , t1 , 0 );
final jundo.runtime.ExtMilieuRef t3 = jundo.runtime.Runtime.asgDoubleObjectMember( tx.getObject() , "startTempo" , t2 , 0 );
final jundo.runtime.ExtMilieuRef t4 = jundo.runtime.Runtime.asgDoubleObjectMember( tx.getObject() , "endTempo" , t3 , 0 );
final labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef z = new labdaw.undo.pdx_TempoViewPaneModel_pdx_PairRef( in , t4 );
return( z );
}
	public static void pdx_initClassMembers( )
{
}

	static
{
pdx_initClassMembers();
}

	public double pdx_ObjectMemberAccess_pdx_getendSecondsNumber( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getDoubleObjectMember( this , "endSecondsNumber" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgendSecondsNumber( final jundo.runtime.ExtMilieuRef mil , final double val )
{
return( jundo.runtime.Runtime.asgDoubleObjectMember( this , "endSecondsNumber" , mil , val ) );
}
	public double pdx_ObjectMemberAccess_pdx_getstartSecondsNumber( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getDoubleObjectMember( this , "startSecondsNumber" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgstartSecondsNumber( final jundo.runtime.ExtMilieuRef mil , final double val )
{
return( jundo.runtime.Runtime.asgDoubleObjectMember( this , "startSecondsNumber" , mil , val ) );
}
	public double pdx_ObjectMemberAccess_pdx_getstartTempo( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getDoubleObjectMember( this , "startTempo" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgstartTempo( final jundo.runtime.ExtMilieuRef mil , final double val )
{
return( jundo.runtime.Runtime.asgDoubleObjectMember( this , "startTempo" , mil , val ) );
}
	public double pdx_ObjectMemberAccess_pdx_getendTempo( final jundo.runtime.ExtMilieuRef mil )
{
return( jundo.runtime.Runtime.getDoubleObjectMember( this , "endTempo" , mil ) );
}
	public jundo.runtime.ExtMilieuRef pdx_ObjectMemberAccess_pdx_asgendTempo( final jundo.runtime.ExtMilieuRef mil , final double val )
{
return( jundo.runtime.Runtime.asgDoubleObjectMember( this , "endTempo" , mil , val ) );
}
	public jundo.runtime.ExtMilieuRef pdxm_setStartTempo( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final double  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1820 = ( this ).pdx_ObjectMemberAccess_pdx_asgstartTempo( pdx_thismilieu , ( in ) );
return( pdx_tmp_1820 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setEndTempo( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final double  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_2300 = ( this ).pdx_ObjectMemberAccess_pdx_asgendTempo( pdx_thismilieu , ( in ) );
return( pdx_tmp_2300 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setStartSecondsNumber( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final double  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_860 = ( this ).pdx_ObjectMemberAccess_pdx_asgstartSecondsNumber( pdx_thismilieu , ( in ) );
return( pdx_tmp_860 );
}
	public jundo.runtime.ExtMilieuRef pdxm_setEndSecondsNumber( final jundo.runtime.ExtMilieuRef pdx_thismilieu , final double  in )
{
final jundo.runtime.ExtMilieuRef pdx_tmp_1340 = ( this ).pdx_ObjectMemberAccess_pdx_asgendSecondsNumber( pdx_thismilieu , ( in ) );
return( pdx_tmp_1340 );
}
	public double pdxm_getEndTempo( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final double pdx_tmp_2060 = ( this ).pdx_ObjectMemberAccess_pdx_getendTempo( pdx_thismilieu );
return( pdx_tmp_2060 );
}
	public double pdxm_getStartTempo( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final double pdx_tmp_1580 = ( this ).pdx_ObjectMemberAccess_pdx_getstartTempo( pdx_thismilieu );
return( pdx_tmp_1580 );
}
	public double pdxm_getStartSecondsNumber( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final double pdx_tmp_620 = ( this ).pdx_ObjectMemberAccess_pdx_getstartSecondsNumber( pdx_thismilieu );
return( pdx_tmp_620 );
}
	public double pdxm_getEndSecondsNumber( final jundo.runtime.ExtMilieuRef pdx_thismilieu )
{
final double pdx_tmp_1100 = ( this ).pdx_ObjectMemberAccess_pdx_getendSecondsNumber( pdx_thismilieu );
return( pdx_tmp_1100 );
}
	}

